pjax: true
minify: true
scheme: Gemini
darkmode: true
avatar:
  url: /images/avatar.jpg
  rotated: true
social:
  Github: "https://github.com/erikh"
  E-Mail: "mailto:erik+blog@hollensbe.org"
  LinkedIn: "https://www.linkedin.com/in/erik-hollensbe"
font:
  global:
    external: false
    family: serif
  codes:
    external: false
    family: monospace
  headings:
    external: false
    family: sans-serif
google_analytics:
  tracking_id: UA-174900471-1
site_state: false
menu:
  home: /
  archives: /archives
