pjax: true
minify: true
scheme: Gemini
darkmode: true
avatar:
  url: /images/avatar.jpg
social:
  Github: "https://github.com/erikh"
  Twitter: "https://twitter.com/erikhollensbe"
  E-Mail: "mailto:erik+blog@hollensbe.org"
font:
  global:
    external: false
    family: Georgia
  codes:
    external: false
    family: Courier New
  headings:
    external: false
    family: Helvetica
google_analytics:
  tracking_id: UA-174900471-1
